### ISSUE TITLE
Remove High Priority Bug  - wged

### ISSUE THREAD

**Issue by mjblowers** [BoiseState/CS471-S19-ProjectWarmup#34]
#1
PlatformManager.java
@BUG HighPriority - wged (2 of 3) ->|
@BUG HighPriority - wged (2 of 3) ->|package com.mucommander;
@BUG HighPriority - wged (2 of 3) ->|

**Comment by mjblowers** [comment]
References issue #1

**Comment by joshchamberlain** [comment]
This is a duplicate of #8. Closing bug.
