### ISSUE TITLE
Remove High Priority Bug - wged

### ISSUE THREAD

**Issue by krisvck** [BoiseState/CS471-S19-ProjectWarmup#63]
References #8 

**Steps to Reproduce:**

```
1. Open in an IDE the file `src/main/java/com/mucommander/desktop/VersionChecker.java`

2. Go to line `97`
```
**Other notes:**
The bug is spread in two other locations:

* `src/main/java/com/mucommander/VersionChecker.java` at line `18`
* `src/main/java/com/mucommander/muCommander.java` at line `18`

**Actual Results:**
Syntax errors are highlighted in the IDE

**Expected Results:**
No syntax errors should be displayed

**Comment by joshchamberlain** [comment]
This is a duplicate of #8. Closing bug.
