### ISSUE TITLE
Remove Medium Priority Bug - odwj

### ISSUE THREAD

**Issue by jedthe3rd** [BoiseState/CS471-S19-ProjectWarmup#94]
References: #2 

**Steps to Reproduce:**

1. Open in an IDE the file `src\main\java\com\mucommander\shell\ShellEncodingListener.java`
2. Go to line `41`

**Actual Results:**

**Expected Results:**

**Other notes:**
Bug also affects `src\main\java\com\mucommander\extension\LookAndFeelFilter.java` on line `18`

**Comment by jedthe3rd** [comment]
@mjblowers made an issue after mine and then fixed the bug. #108

**Comment by jedthe3rd** [comment]
Oh, he didn't fix both files though. Reopening.

**Comment by mjblowers** [comment]
@jedthe3rd my bad - entered the bug as 'odjw' hence why I didn't see this one populate.
